{
  "hash": "b9600ecd573246b4ade8b09c3edb5518",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Does the Savitzky-Golay setting matter?\"\nsubtitle: \"Compare a few contrasting Savitzky-Golay settings under repeated cross-validation.\"\nauthor: Franck Albinet\ndate: last-modified\nformat:\n  html:\n    toc: true\n    theme: cosmo\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\nThe other pages fix the Savitzky-Golay (SG) parameters at `w = 15`, `p = 3`, `m = 1`. These are sensible defaults from practice, not values fitted to any dataset. This page checks whether the choice matters on the RT data. It compares a few contrasting SG settings, and a model without SG, with the same repeated cross-validation as [Evaluating performance](../6-evaluating-performance.qmd). Read that page first: this one reuses its split, its folds, and its one-standard-error bound, and does not explain them again.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(here)\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(plsmod)\nsource(here(\"R\", \"prepare_data.R\"))\nsource(here(\"R\", \"steps.R\"))\nsource(here(\"R\", \"split.R\"))\ntheme_set(theme_bw())\ntidymodels_prefer()\n```\n:::\n\n\nReferences:\n\n- [Tidy Modeling with R, chapter 13: Grid search](https://www.tmwr.org/grid-search.html)\n- [`prospectr::savitzkyGolay()`](https://cran.r-project.org/web/packages/prospectr/vignettes/prospectr.html)\n- Savitzky, A. and Golay, M. J. E. (1964). Smoothing and differentiation of data by simplified least squares procedures. *Analytical Chemistry*, 36(8), 1627–1639.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nSPECTRA_DIR = here(\"data/RT_spectra\")\nSOIL_PROP_FILE = here(\"data/RT_wetchem_soildata.csv\")\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nTARGET <- \"carbon_tot_perc\"\n\nsource(here(\"R\", \"config.R\"), echo = TRUE, keep.source = TRUE, max.deparse.length = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n> # Shared settings for the course pages.\n> # Each page loads it with source(..., echo = TRUE), which prints every line,\n> # so the rendered page shows each value it uses.\n> # Change a value here, re-render, and every page uses the new value.\n> \n> # Samples left out of modelling.\n> # Outlier detection flags their spectra as the two most unusual.\n> EXCLUDED_SAMPLES <- c(\"RT_44\", \"RT_42\")\n\n> # Spectral preprocessing\n> RESAMPLING_GRID <- seq(3995, 600, by = -5)  # target wavenumbers, in cm-1\n\n> SG_W <- 15L  # Savitzky-Golay window width, in grid points\n\n> SG_P <- 3L   # Savitzky-Golay polynomial order\n\n> SG_M <- 1L   # Savitzky-Golay derivative order (0 = smoothing only)\n\n> # Cutoff on the scaled Mahalanobis distance of a spectrum.\n> # Chosen by eye on the Outlier detection page, reused at inference.\n> OUTLIER_CUTOFF <- 1.9\n```\n\n\n:::\n\n```{.r .cell-code}\n# --- PLS --------------------------------------------------------------------\nNUM_COMP <- 2:20\n```\n:::\n\n\nThe shared settings come from [`R/config.R`](https://github.com/franckalbinet/tidy-mirs/blob/main/R/config.R). [The full pipeline](../1-full-pipeline.qmd) explains how it works.\n\n## Data, split, and folds\n\nThese are exactly the steps of [Evaluating performance](../6-evaluating-performance.qmd): `EXCLUDED_SAMPLES` left out, a Kennard-Stone split, and 10-fold cross-validation repeated 10 times on the training set. The test set is not used on this page.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata <- prepare_rt(SPECTRA_DIR, SOIL_PROP_FILE) |> filter(!smp_id %in% EXCLUDED_SAMPLES)\n\nsplit <- kennard_stone_split(data, prop = 50/70, cols = starts_with(\"wn_\"))\n\nset.seed(123)\nfolds <- vfold_cv(\n  training(split),\n  v = 10,\n  repeats = 10,\n  strata = all_of(TARGET),\n  breaks = 2\n)\n```\n:::\n\n\n## What the three parameters do\n\nSG fits a polynomial of degree `p` to the `w` points centred on each wavenumber. It then replaces that point with the fitted value (`m = 0`) or a derivative of the fitted polynomial (`m = 1` or `m = 2`).\n\n- `w`, the window size, sets how much the spectrum is smoothed. A wider window averages away more noise, but it also flattens narrow absorption bands. `w` counts points on the resampled grid, not wavenumbers. Here the grid has one point every 5 cm⁻¹, so `w = 7` spans 30 cm⁻¹ and `w = 21` spans 100 cm⁻¹.\n- `p`, the polynomial degree, sets how closely the fit can follow the shape inside the window. A higher degree keeps sharper peaks, but smooths less.\n- `m`, the derivative order, sets what is read off the fit. `m = 0` smooths only. `m = 1` removes a constant baseline offset. `m = 2` also removes a linear baseline slope. Each derivative also amplifies noise, which a wider window has to compensate for.\n\n`w` must be odd, so that the window has a centre point. `m` must not exceed `p`.\n\n## The settings compared\n\nThe settings below cross the three derivative orders with a narrow and a wide window. `p = 2` is valid for all three derivative orders, so it stays fixed and only one thing changes at a time. The course default is added as a reference.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsg_settings <- tribble(\n  ~w,  ~p, ~m,\n   7L, 2L, 0L,\n  21L, 2L, 0L,\n   7L, 2L, 1L,\n  21L, 2L, 1L,\n   7L, 2L, 2L,\n  21L, 2L, 2L,\n  15L, 3L, 1L\n)\n```\n:::\n\n\n## Models\n\nThe recipe is the one from the other pages, with `tune()` in place of the three SG values. A second recipe leaves out `step_sg()`. It answers a simpler question: does SG help at all?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nspc_cols <- names(data)[startsWith(names(data), \"wn_\")]\nmeta_cols <- setdiff(names(data), c(TARGET, spc_cols))\n\nrec_base <- recipe(data) |>\n  update_role(all_of(TARGET),  new_role = \"outcome\") |>\n  update_role(all_of(spc_cols), new_role = \"predictor\") |>\n  update_role(all_of(meta_cols), new_role = \"metadata\") |>\n  step_log(all_outcomes(), base = 10) |>\n  step_resample(grid = RESAMPLING_GRID) |>\n  step_snv()\n\nrec_sg <- rec_base |>\n  step_sg(w = tune(), p = tune(), m = tune())\n\npls_spec <- pls(num_comp = tune()) |>\n  set_engine(\"mixOmics\") |>\n  set_mode(\"regression\")\n\nwf_base <- workflow() |> add_recipe(rec_base) |> add_model(pls_spec)\nwf_sg   <- workflow() |> add_recipe(rec_sg)   |> add_model(pls_spec)\n```\n:::\n\n\nEach SG setting is crossed with 2 to 20 PLS components, as on [Evaluating performance](../6-evaluating-performance.qmd).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngrid_sg <- expand_grid(sg_settings, num_comp = NUM_COMP)\n```\n:::\n\n\nEach SG setting has a cost. It changes the spectra, so in every fold the recipe must be prepped again and PLS fitted again. The number of components adds almost no cost. PLS builds its components one after the other, and adding a component does not change the ones before it. So a model fitted with 20 components already contains the models with 2 to 19 components: to predict with 5 components, it uses only the first 5. `tune_grid()` uses this, and fits PLS only once per SG setting in each fold. With the model without SG, that is 8 settings × 100 folds, 800 fits.\n\n`cache: true` stores the result of the two tuning chunks on disk. Later renders reuse it, as long as the chunk code and the objects hashed in `cache.extra` are unchanged. `rlang::hash()` turns those objects into one short string, which changes whenever any of them changes. To run the tuning again, delete the `tuning-savitzky-golay_cache` folder.\n\n\n::: {.cell layout-align=\"center\" cache.extra='8bbab1c3773d800c7b8707149f9a7604'}\n\n```{.r .cell-code}\nres_base <- tune_grid(\n  wf_base,\n  resamples = folds,\n  grid = tibble(num_comp = NUM_COMP),\n  metrics = metric_set(rmse)\n)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\" cache.extra='502f7499899656ec3abb3d39fa1a2fc7'}\n\n```{.r .cell-code}\nres_sg <- tune_grid(\n  wf_sg,\n  resamples = folds,\n  grid = grid_sg,\n  metrics = metric_set(rmse)\n)\n```\n:::\n\n\n## Results\n\nThe results of both searches go into one table, with a label for each setting.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrmse_res <- bind_rows(\n  collect_metrics(res_base) |> mutate(setting = \"no SG\"),\n  collect_metrics(res_sg)   |> mutate(setting = glue::glue(\"w={w}, p={p}, m={m}\"))\n) |>\n  mutate(default = setting == glue::glue(\"w={SG_W}, p={SG_P}, m={SG_M}\"))\n```\n:::\n\n\n### RMSE against the number of components\n\nEach line is one setting.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrmse_res |>\n  ggplot(aes(x = num_comp, y = mean, colour = setting)) +\n  geom_line() +\n  labs(x = \"Number of PLS components\", y = \"RMSE (log10 units)\", colour = NULL,\n       title = \"CV RMSE by preprocessing setting\")\n```\n\n::: {.cell-output-display}\n![](tuning-savitzky-golay_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=864}\n:::\n:::\n\n\n### Best RMSE of each setting\n\nFor each setting, the table below keeps the number of components with the lowest mean RMSE. `bound` is the one-standard-error bound of the overall best: its mean RMSE plus its standard error.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbest_per_setting <- rmse_res |>\n  group_by(setting) |>\n  slice_min(mean, n = 1, with_ties = FALSE) |>\n  ungroup()\n\nbest_row <- best_per_setting |> slice_min(mean, n = 1, with_ties = FALSE)\nbound    <- best_row$mean + best_row$std_err\n\nbest_per_setting |>\n  mutate(within_bound = mean <= bound) |>\n  arrange(mean) |>\n  select(setting, num_comp, mean, std_err, within_bound)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 5\n  setting        num_comp  mean std_err within_bound\n  <glue>            <int> <dbl>   <dbl> <lgl>       \n1 w=7, p=2, m=0        20 0.133 0.00643 TRUE        \n2 w=21, p=2, m=0        8 0.137 0.00433 TRUE        \n3 w=21, p=2, m=2       16 0.139 0.00485 TRUE        \n4 no SG                 8 0.140 0.00474 FALSE       \n5 w=21, p=2, m=1        7 0.145 0.00464 FALSE       \n6 w=15, p=3, m=1        7 0.146 0.00494 FALSE       \n7 w=7, p=2, m=1         7 0.147 0.00489 FALSE       \n8 w=7, p=2, m=2         9 0.179 0.00628 FALSE       \n```\n\n\n:::\n:::\n\n\nThe plot shows the same values. The error bars show ±1 standard error. The dashed line is the bound. The default is in red.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbest_per_setting |>\n  ggplot(aes(x = mean, y = fct_reorder(setting, mean, .desc = TRUE), colour = default)) +\n  geom_vline(xintercept = bound, linetype = \"22\") +\n  geom_errorbar(aes(xmin = mean - std_err, xmax = mean + std_err), width = 0, orientation = \"y\") +\n  geom_point() +\n  scale_colour_manual(values = c(`FALSE` = \"grey20\", `TRUE` = \"red\"), guide = \"none\") +\n  labs(x = \"Lowest mean RMSE over the number of components (log10 units)\", y = NULL,\n       title = \"Settings ranked by their best CV RMSE\")\n```\n\n::: {.cell-output-display}\n![](tuning-savitzky-golay_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn_within   <- sum(best_per_setting$mean <= bound)\nspread_sg  <- diff(range(best_per_setting$mean))\ncomp_range <- rmse_res |> filter(setting == best_row$setting) |> pull(mean) |> range() |> diff()\ndefault_row <- best_per_setting |> filter(default)\n```\n:::\n\n\n3 of the 8 settings are inside the bound. Between the best and the worst setting, the lowest mean RMSE varies by 0.046. For the best setting alone, the RMSE varies by 0.12 across the number of components. On this dataset, the number of components matters more than the preprocessing setting.\n\nThe standard errors are also too small, as [Evaluating performance](../6-evaluating-performance.qmd) explains: the 100 fold scores are not independent. The real uncertainty is wider than the error bars, so the settings are even harder to separate than the plot suggests.\n\n## What this means in practice\n\nWith 48 training samples, the data cannot reliably separate most SG settings. The ranking is also unstable. Removing a single sample, `RT_42`, reordered most of the table and moved several settings across the bound. Three points still stand out:\n\n- **Settings that amplify noise do worse.** Each derivative amplifies noise, and a narrow window averages little of it away. The second derivative with `w = 7`, a window of 30 cm⁻¹, is clearly the worst setting.\n- **Settings without a derivative do well here.** Smoothing alone, or no SG at all, scores at or near the top. PLS combines hundreds of wavenumbers into each component, which already averages away much of the noise that SG smoothing would remove.\n- **The course default is not among the best here.** Its lowest mean RMSE is 0.146, against a bound of 0.139. The gap is small. One sample was enough to move the default from inside the bound to outside it, so this is weak evidence against the setting.\n\nThe choice of SG setting is therefore not worth a long search: avoid settings that amplify noise, and keep a standard one. The number of PLS components matters much more, and tuning it is essential.\n\nThe course keeps `w = 15`, `p = 3`, `m = 1` as its default. The first derivative is a standard choice for MIR spectra: it removes baseline shifts, and [Feature engineering](../4-feature-engineering.qmd) shows what it does to a spectrum. To try another setting on every page, change `SG_W`, `SG_P` and `SG_M` in `R/config.R` and render the pages again. Compare settings with cross-validation results, as on this page, not with the test score. Choosing with the test set makes its score optimistic.\n\nThis holds for this dataset, not in general. Two things can change the answer:\n\n- **More samples.** With thousands of samples, like the [OSSL](../8-preparing-ossl.qmd) sample, the error bars shrink. Differences between settings that are hidden here can become visible. The same check is then worth running, with a validation set instead of repeated cross-validation to keep the cost down.\n- **The resolution of the spectral grid.** `w` counts grid points. On a grid with one point every 10 cm⁻¹, `w = 21` spans 200 cm⁻¹, not 100. A setting tuned on one grid does not carry over to another grid as it is.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}